-- Additive PostgreSQL replacement for the rescued Guardian Beta D1 schema.
-- Declared SQLite affinities are retained: integer fields remain integers and
-- timestamp strings remain text, with safe timestamp parsing in window queries.

CREATE SCHEMA IF NOT EXISTS cf_echo_guardian_beta;

CREATE OR REPLACE FUNCTION cf_echo_guardian_beta.safe_timestamptz(value text)
RETURNS timestamptz
LANGUAGE plpgsql
IMMUTABLE
STRICT
AS $safe_timestamp$
BEGIN
    IF value ~ '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}([.]\d+)?$' THEN
        RETURN (value || ' UTC')::timestamptz;
    END IF;
    IF value ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}([.]\d+)?(Z|[+-]\d{2}:\d{2})$' THEN
        RETURN value::timestamptz;
    END IF;
    RETURN NULL;
EXCEPTION WHEN datetime_field_overflow OR invalid_datetime_format THEN
    RETURN NULL;
END
$safe_timestamp$;

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.creations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name text NOT NULL,
    reason text,
    description text,
    lines_of_code integer,
    github_repo text,
    deployed integer DEFAULT 0,
    created_at text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.enhancement_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name text NOT NULL,
    priority integer DEFAULT 5,
    type text NOT NULL,
    analysis text,
    status text DEFAULT 'pending',
    claimed_by text,
    created_at text DEFAULT '',
    completed_at text
);

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.enhancements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name text NOT NULL,
    type text NOT NULL,
    description text,
    files_changed text,
    code_before text,
    code_after text,
    ai_reasoning text,
    github_url text,
    deployed integer DEFAULT 0,
    reverted integer DEFAULT 0,
    created_at text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.guardian_state (
    key text PRIMARY KEY,
    value text,
    updated_at text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.health_checks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name text NOT NULL,
    status text NOT NULL,
    status_code integer,
    latency_ms integer,
    version text,
    error text,
    checked_at text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.incidents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name text NOT NULL,
    type text NOT NULL,
    severity text NOT NULL DEFAULT 'warning',
    description text,
    auto_resolved integer DEFAULT 0,
    resolved_at text,
    created_at text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.partner_health (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_name text NOT NULL,
    status text NOT NULL,
    latency_ms integer,
    consecutive_failures integer DEFAULT 0,
    last_success text,
    resurrection_attempted integer DEFAULT 0,
    checked_at text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.job_runs (
    run_id uuid PRIMARY KEY,
    job_name text NOT NULL,
    idempotency_key text NOT NULL UNIQUE,
    status text NOT NULL CHECK (status IN ('running','completed','failed','skipped')),
    summary_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Root-owned evidence. The service role may read but cannot mint or alter it.
CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.d1_import_receipts (
    receipt_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_sha256 character(64) NOT NULL UNIQUE,
    source_counts jsonb NOT NULL,
    imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.migration_receipts (
    receipt_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    candidate_release text NOT NULL,
    active_release text NOT NULL,
    event_name text NOT NULL CHECK (event_name IN (
        'provenance_verified',
        'staging_smoke',
        'production_candidate_active',
        'production_smoke',
        'rollback_smoke'
    )),
    rescued_source_sha256 character(64) NOT NULL,
    normalized_source_sha256 character(64) NOT NULL,
    repository_source_sha256 character(64) NOT NULL,
    service_dir text NOT NULL,
    unit_name text NOT NULL,
    health_state text NOT NULL CHECK (health_state IN ('verified', 'healthy')),
    recorded_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (candidate_release, event_name)
);

CREATE TABLE IF NOT EXISTS cf_echo_guardian_beta.active_release_attestations (
    attestation_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    active_release text NOT NULL,
    rescued_source_sha256 character(64) NOT NULL,
    normalized_source_sha256 character(64) NOT NULL,
    repository_source_sha256 character(64) NOT NULL,
    health_state text NOT NULL CHECK (health_state='healthy'),
    recorded_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS guardian_state_key_uidx
    ON cf_echo_guardian_beta.guardian_state(key);
CREATE INDEX IF NOT EXISTS health_checks_worker_checked_idx
    ON cf_echo_guardian_beta.health_checks(worker_name, checked_at DESC);
CREATE INDEX IF NOT EXISTS health_checks_status_checked_idx
    ON cf_echo_guardian_beta.health_checks(status, checked_at DESC);
CREATE INDEX IF NOT EXISTS health_checks_checked_ts_idx
    ON cf_echo_guardian_beta.health_checks(
        cf_echo_guardian_beta.safe_timestamptz(checked_at) DESC
    );
CREATE INDEX IF NOT EXISTS incidents_worker_resolved_idx
    ON cf_echo_guardian_beta.incidents(worker_name, resolved_at, created_at DESC);
CREATE INDEX IF NOT EXISTS enhancement_queue_worker_status_idx
    ON cf_echo_guardian_beta.enhancement_queue(worker_name, status, created_at DESC);
CREATE INDEX IF NOT EXISTS partner_health_checked_idx
    ON cf_echo_guardian_beta.partner_health(checked_at DESC);
CREATE INDEX IF NOT EXISTS job_runs_job_started_idx
    ON cf_echo_guardian_beta.job_runs(job_name, started_at DESC);
CREATE INDEX IF NOT EXISTS migration_receipts_event_recorded_idx
    ON cf_echo_guardian_beta.migration_receipts(event_name, recorded_at DESC);
CREATE INDEX IF NOT EXISTS active_release_attestations_recorded_idx
    ON cf_echo_guardian_beta.active_release_attestations(recorded_at DESC);

GRANT USAGE ON SCHEMA cf_echo_guardian_beta TO "echo-guardian-beta";
GRANT SELECT ON ALL TABLES IN SCHEMA cf_echo_guardian_beta TO "echo-guardian-beta";
GRANT INSERT ON cf_echo_guardian_beta.health_checks,
                cf_echo_guardian_beta.incidents,
                cf_echo_guardian_beta.partner_health,
                cf_echo_guardian_beta.enhancement_queue,
                cf_echo_guardian_beta.guardian_state,
                cf_echo_guardian_beta.job_runs TO "echo-guardian-beta";
GRANT UPDATE ON cf_echo_guardian_beta.incidents,
                cf_echo_guardian_beta.guardian_state,
                cf_echo_guardian_beta.job_runs TO "echo-guardian-beta";
GRANT USAGE, SELECT ON SEQUENCE
    cf_echo_guardian_beta.health_checks_id_seq,
    cf_echo_guardian_beta.incidents_id_seq,
    cf_echo_guardian_beta.partner_health_id_seq,
    cf_echo_guardian_beta.enhancement_queue_id_seq TO "echo-guardian-beta";
REVOKE ALL ON cf_echo_guardian_beta.d1_import_receipts,
              cf_echo_guardian_beta.migration_receipts,
              cf_echo_guardian_beta.active_release_attestations
    FROM "echo-guardian-beta";
GRANT SELECT ON cf_echo_guardian_beta.d1_import_receipts,
                cf_echo_guardian_beta.migration_receipts,
                cf_echo_guardian_beta.active_release_attestations
    TO "echo-guardian-beta";
